{
  "FILENAME": "python2-zope-exceptions-4.3-3-any.pkg.tar.xz",
  "NAME": "python2-zope-exceptions",
  "BASE": "python-zope-exceptions",
  "VERSION": "4.3-3",
  "DESC": "Generic exceptions and implementations for Zope",
  "CSIZE": "26400",
  "ISIZE": "192608",
  "MD5SUM": "c615ac9e55db317463971f19f8d125cf",
  "SHA256SUM": "4e2fb03b79c92a71b63e2f34cf220611a35dc1f1a191308870fbcdc1b2c2561f",
  "PGPSIG": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAl28MikACgkQeGxj8zDXy5J3LRAAu95p3iyAkBO7LctbR0uK1BhuhbaFcp1YjS05HKoZ/F2ygg5rA7zpe7cOdUJPUa+90pTEWd/WQ/N6ARm8OYnwWlGcmsaMVvGI+p3W5IO5VZGGZ+HTqG6suuTJFgg0fzCSRIDrpGlxlK/tIYm80fEuE4u/VAD0G7HTfjWKfJi50cXqARjlQXqnkBAQT3J9RYMVxdwTpjfGG1gAOTjQy+cpx9k1W9bWEuwpYD5ehW2QRRbLr/h9WOj2wUk7A4uhVcXjC9EnyQwkoFAoBK/eGkJZVYbfdscsmYJ6F9R3DXi41HMpbqbnk4Icdj5GWJ8MZl4PBxy6+JUOctk78OTJ/4sOZK1WCnHz5BHQTDWebUmLuHg40ph3GiP+0XHrOcSHsXkVKRhhC1I4wBS4oQZ2lGMVp8JpfUl8BeRCAJymfM9AdpoXEg3vWM/1dKRNBSiMvrFyBfBXD3HHc36LYdwDRPncJAEys/c5aNoqRsb9vyYoBbHxkvHxYpg75XWRK7mB9IOPF+Yzk3cO3whM9hniZjriLJm0QOySSCbFL2G9IZAh20CoRApUq2GpGobMeHd7EJ6qjk6bzRGA8eFRZRt9N29exC5HEJldVjBkCTOiJpUDjHdW+zd9CLTJpRtH0hkM3HANa60LiXU0omx9J9uwkBvJK3bnTaqbHNqYeg7O74sPy+8=",
  "URL": "https://github.com/zopefoundation/zope.exceptions",
  "LICENSE": "ZPL",
  "ARCH": "any",
  "BUILDDATE": "1572614658",
  "PACKAGER": "Felix Yan <felixonmars@archlinux.org>",
  "PROVIDES": [
    ""
  ],
  "DEPENDS": [
    "python2-setuptools",
    "python2-zope-interface"
  ]
}